excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://joshparolin.github.io
title: Forcing Mechanisms
tagline: Musings on life, business and technology
description: Musings on life, business and technology
paginate: 5
